import type { Language } from './models';
export const REMARKS: Record<Language, string[]> = {
  en: [
    'You did this.',
    'This was yours to keep.',
    'A small light, noticed.',
    'You were here for this.',
    'Quiet, and real.',
    'This counts.',
    'You folded it in time.',
    'A Kiseki, because you saw it.',
    'Held, not hurried.',
    'Even this was enough.',
    'You gave it a place.',
    'The jar will remember.',
    'Soft, and true.',
    'You made room for it.',
    'A little miracle, kept.',
    'This belongs to you.',
  ],
  el: [
    'Το έκανες εσύ.',
    'Αυτό ήταν δικό σου να το κρατήσεις.',
    'Ένα μικρό φως, που το είδες.',
    'Ήσουν εδώ γι’ αυτό.',
    'Ήσυχο, και αληθινό.',
    'Αυτό μετράει.',
    'Το δίπλωσες στην ώρα του.',
    'Ένα Kiseki, επειδή το πρόσεξες.',
    'Φυλαγμένο, όχι βιαστικό.',
    'Ακόμη κι αυτό αρκούσε.',
    'Του έδωσες έναν τόπο.',
    'Το βάζο θα το θυμάται.',
    'Απαλό, και αληθινό.',
    'Έκανες χώρο γι’ αυτό.',
    'Ένα μικρό θαύμα, φυλαγμένο.',
    'Αυτό σου ανήκει.',
  ],
  ja: [
    'あなたが、できたこと。',
    '残すに値するもの。',
    '小さな光に、気づいた。',
    'その場に、いた。',
    '静かで、ほんとう。',
    'これは、数えられる。',
    '間に合うように、折った。',
    '気づいたから、Kiseki。',
    '急がず、残した。',
    'これだけで、足りた。',
    '居場所を、あげた。',
    '瓶は、覚えている。',
    'やさしくて、ほんとう。',
    '場所を、つくった。',
    '小さな奇跡を、残した。',
    'あなたのもの。',
  ],
};
export function openingRemark(language: Language, random = Math.random) {
  const list = REMARKS[language];
  return list[Math.min(list.length - 1, Math.floor(random() * list.length))];
}
export const TITLES: Record<Language, string[]> = {
  en: [
    'A Kiseki worth keeping',
    'Something small, yours',
    'A light you kept',
    'What you noticed',
    'A quiet win',
    "Tonight's little miracle",
    'Held with care',
    'A star from this day',
    'Worth remembering',
    'Kept here, gently',
    'Yours, in the jar',
    'This one counts',
    'A little miracle, kept',
    'Soft light, remembered',
    'Folded in, with love',
    'Tonight you noticed',
  ],
  el: [
    'Ένα Kiseki που αξίζει',
    'Κάτι μικρό, δικό σου',
    'Φως που φύλαξες',
    'Αυτό που πρόσεξες',
    'Μια ήσυχη νίκη',
    'Το μικρό θαύμα της στιγμής',
    'Κρατημένο με φροντίδα',
    'Ένα αστέρι από σήμερα',
    'Αξίζει να το θυμάσαι',
    'Εδώ φυλάχτηκε',
    'Ένα Kiseki, δικό σου',
    'Αυτό μετράει',
    'Ένα μικρό θαύμα, δικό σου',
    'Απαλό φως, φυλαγμένο',
    'Διπλωμένο με αγάπη',
    'Απόψε το πρόσεξες',
  ],
  ja: [
    '大切にしたいKiseki',
    '小さな、あなたのもの',
    '残した光',
    '気づいたこと',
    '静かな、小さな勝ち',
    '今の小さな奇跡',
    'やさしく、残した',
    '今日の星',
    '覚えておきたい',
    'ここに、置いた',
    '瓶の中の、あなた',
    'これは、数えられる',
    '小さな奇跡を、残した',
    'やわらかい光',
    '愛をこめて、折った',
    '今夜、気づいた',
  ],
};
export function memoryTitle(language: Language, random = Math.random) {
  const list = TITLES[language];
  return list[Math.min(list.length - 1, Math.floor(random() * list.length))];
}
